ARG cuda_version=9.0
ARG cudnn_version=7
ARG python_version=3.6

FROM nvidia/cuda:${cuda_version}-cudnn${cudnn_version}-devel

# Install system packages
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
      bzip2 \
      g++ \
      git \
      graphviz \
      libgl1-mesa-glx \
      libhdf5-dev \
      openmpi-bin \
      wget
RUN rm -rf /var/lib/apt/lists/*

# Install Miniconda
ENV CONDA_DIR /opt/conda
ENV PATH $CONDA_DIR/bin:$PATH
RUN wget --quiet --no-check-certificate https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    /bin/bash /Miniconda3-latest-Linux-x86_64.sh -f -b -p $CONDA_DIR && \
    rm Miniconda3-latest-Linux-x86_64.sh && \
    echo export PATH=$CONDA_DIR/bin:'$PATH' > /etc/profile.d/conda.sh

# Install Tensorflow, Keras, Python packages
RUN conda install -y python=${python_version}
RUN pip --default-timeout=1000 install --upgrade pip
RUN pip --default-timeout=1000 install tensorflow-gpu keras spacy
RUN conda install \
      bcolz \
      h5py \
      matplotlib \
      mkl \
      nose \
      notebook \
      Pillow \
      pandas \
      pygpu \
      pyyaml \
      scikit-learn \
      six \
      gensim \
      pandas
RUN conda clean -yt

# Set up volume
RUN mkdir /data

# Set up Jupyter with password and run
WORKDIR /data
EXPOSE 8888
CMD jupyter notebook --allow-root --port=8888 --ip=* --no-browser